name: "non-empty git status"
description: "Fails if git status is non-empty."
runs:
  using: "composite"
  steps:
    - name: "git status"
      shell: bash
      run: test -z "$(git status --porcelain)"
