name: checks

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v4.1.1
        
    - uses: actions/setup-node@v4.0.1
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - uses: actions/setup-java@v4.7.0
      with:
        java-version: 21
        distribution: temurin
        cache: 'gradle'

    - uses: amyu/setup-android@v4

    - name: npm install
      run: |
        . environment
        npm ci

    - name: prebuild
      run: |
        . environment
        expo prebuild

    - name: npm run lint
      run: |
        . environment
        npm run lint

    - name: tsc
      run: |
        . environment
        tsc

    - name: npm test
      run: |
        . environment
        npm test

    - name: npm run android-test
      run: |
        . environment
        npm run android-test

    - name: test report - android gradle test
      uses: actions/upload-artifact@v4.3.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: android-test
        path: build/reports/tests/testDebugUnitTest/
