name: checks

on: push

jobs:
  
  js:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v4.1.1        
    - uses: actions/setup-node@v4.0.1
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - name: npm install
      run: |
        . environment
        npm ci
    - name: npm run lint
      run: |
        . environment
        npm run lint
    - name: tsc
      run: |
        . environment
        tsc
    - name: npm test
      run: |
        . environment
        npm test

  android:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v4.1.1
        
    - uses: actions/setup-node@v4.0.1
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - uses: actions/setup-java@v4.7.0
      with:
        java-version: 21
        distribution: temurin
        cache: 'gradle'

    - uses: amyu/setup-android@v4

    - name: npm install
      run: |
        . environment
        npm ci

    - name: prebuild
      run: |
        . environment
        expo prebuild

    - name: npm run android-test
      run: |
        . environment
        npm run android-test

    - name: test report - android gradle test
      uses: actions/upload-artifact@v4.3.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: android-test
        path: |
          android/app/build/reports/tests
          modules/expo-experiments/android/build/reports/tests

    - name: release apk build
      run: |
        . environment
        npm run android-release-apk

    - name: upload release apk
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk

  android-test:
    runs-on: ubuntu-24.04
    needs: android # for the apk

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: npm install
        run: |
          . environment
          npm ci

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: maestro
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            . environment
            adb install app-release.apk
            npm run maestro
